# Generated by Django 4.1.5 on 2023-02-04 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketApp', '0005_alter_employee_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskAssigned',
        ),
    ]
