# Generated by Django 4.1.5 on 2023-02-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketApp', '0006_delete_taskassigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(limit_choices_to={'role': 'DEV'}, related_name='dev', to='ticketApp.employee'),
        ),
    ]
