# Generated by Django 4.1.5 on 2023-02-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketApp', '0009_alter_task_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_to',
            field=models.ManyToManyField(limit_choices_to={'role': 'PM'}, related_name='pm', to='ticketApp.employee'),
        ),
    ]
